// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: video_processing.proto

#include "video_processing.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

extern PROTOBUF_INTERNAL_EXPORT_video_5fprocessing_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_ImageData_video_5fprocessing_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_video_5fprocessing_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_ImagePair_video_5fprocessing_2eproto;
namespace video_processing {
class ImageDataDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ImageData> _instance;
} _ImageData_default_instance_;
class ImagePairDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ImagePair> _instance;
} _ImagePair_default_instance_;
class VideoFrameDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<VideoFrame> _instance;
  const ::video_processing::ImageData* single_image_;
  const ::video_processing::ImagePair* image_pair_;
  ::google::protobuf::internal::ArenaStringPtr command_;
} _VideoFrame_default_instance_;
}  // namespace video_processing
static void InitDefaultsImageData_video_5fprocessing_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::video_processing::_ImageData_default_instance_;
    new (ptr) ::video_processing::ImageData();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::video_processing::ImageData::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ImageData_video_5fprocessing_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsImageData_video_5fprocessing_2eproto}, {}};

static void InitDefaultsImagePair_video_5fprocessing_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::video_processing::_ImagePair_default_instance_;
    new (ptr) ::video_processing::ImagePair();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::video_processing::ImagePair::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_ImagePair_video_5fprocessing_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsImagePair_video_5fprocessing_2eproto}, {
      &scc_info_ImageData_video_5fprocessing_2eproto.base,}};

static void InitDefaultsVideoFrame_video_5fprocessing_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::video_processing::_VideoFrame_default_instance_;
    new (ptr) ::video_processing::VideoFrame();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::video_processing::VideoFrame::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_VideoFrame_video_5fprocessing_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsVideoFrame_video_5fprocessing_2eproto}, {
      &scc_info_ImageData_video_5fprocessing_2eproto.base,
      &scc_info_ImagePair_video_5fprocessing_2eproto.base,}};

void InitDefaults_video_5fprocessing_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_ImageData_video_5fprocessing_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ImagePair_video_5fprocessing_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_VideoFrame_video_5fprocessing_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_video_5fprocessing_2eproto[3];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors_video_5fprocessing_2eproto[3];
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_video_5fprocessing_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_video_5fprocessing_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::video_processing::ImageData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::video_processing::ImageData, width_),
  PROTOBUF_FIELD_OFFSET(::video_processing::ImageData, height_),
  PROTOBUF_FIELD_OFFSET(::video_processing::ImageData, pixel_format_),
  PROTOBUF_FIELD_OFFSET(::video_processing::ImageData, encoding_),
  PROTOBUF_FIELD_OFFSET(::video_processing::ImageData, image_data_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::video_processing::ImagePair, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::video_processing::ImagePair, original_),
  PROTOBUF_FIELD_OFFSET(::video_processing::ImagePair, processed_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::video_processing::VideoFrame, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::video_processing::VideoFrame, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::video_processing::VideoFrame, frame_id_),
  PROTOBUF_FIELD_OFFSET(::video_processing::VideoFrame, timestamp_),
  PROTOBUF_FIELD_OFFSET(::video_processing::VideoFrame, sender_id_),
  PROTOBUF_FIELD_OFFSET(::video_processing::VideoFrame, frame_type_),
  offsetof(::video_processing::VideoFrameDefaultTypeInternal, single_image_),
  offsetof(::video_processing::VideoFrameDefaultTypeInternal, image_pair_),
  offsetof(::video_processing::VideoFrameDefaultTypeInternal, command_),
  PROTOBUF_FIELD_OFFSET(::video_processing::VideoFrame, content_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::video_processing::ImageData)},
  { 10, -1, sizeof(::video_processing::ImagePair)},
  { 17, -1, sizeof(::video_processing::VideoFrame)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::video_processing::_ImageData_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::video_processing::_ImagePair_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::video_processing::_VideoFrame_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_video_5fprocessing_2eproto = {
  {}, AddDescriptors_video_5fprocessing_2eproto, "video_processing.proto", schemas,
  file_default_instances, TableStruct_video_5fprocessing_2eproto::offsets,
  file_level_metadata_video_5fprocessing_2eproto, 3, file_level_enum_descriptors_video_5fprocessing_2eproto, file_level_service_descriptors_video_5fprocessing_2eproto,
};

const char descriptor_table_protodef_video_5fprocessing_2eproto[] =
  "\n\026video_processing.proto\022\020video_processi"
  "ng\"\246\001\n\tImageData\022\r\n\005width\030\001 \001(\r\022\016\n\006heigh"
  "t\030\002 \001(\r\0223\n\014pixel_format\030\003 \001(\0162\035.video_pr"
  "ocessing.PixelFormat\0221\n\010encoding\030\004 \001(\0162\037"
  ".video_processing.ImageEncoding\022\022\n\nimage"
  "_data\030\005 \001(\014\"j\n\tImagePair\022-\n\010original\030\001 \001"
  "(\0132\033.video_processing.ImageData\022.\n\tproce"
  "ssed\030\002 \001(\0132\033.video_processing.ImageData\""
  "\373\001\n\nVideoFrame\022\020\n\010frame_id\030\001 \001(\004\022\021\n\ttime"
  "stamp\030\002 \001(\001\022\021\n\tsender_id\030\003 \001(\t\022/\n\nframe_"
  "type\030\004 \001(\0162\033.video_processing.FrameType\022"
  "3\n\014single_image\030\005 \001(\0132\033.video_processing"
  ".ImageDataH\000\0221\n\nimage_pair\030\006 \001(\0132\033.video"
  "_processing.ImagePairH\000\022\021\n\007command\030\007 \001(\t"
  "H\000B\t\n\007content*V\n\tFrameType\022\013\n\007UNKNOWN\020\000\022"
  "\022\n\016CAPTURED_FRAME\020\001\022\023\n\017PROCESSED_FRAME\020\002"
  "\022\023\n\017CONTROL_MESSAGE\020\003*)\n\013PixelFormat\022\007\n\003"
  "BGR\020\000\022\007\n\003RGB\020\001\022\010\n\004GRAY\020\002*+\n\rImageEncodin"
  "g\022\010\n\004JPEG\020\000\022\007\n\003PNG\020\001\022\007\n\003RAW\020\002b\006proto3"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_video_5fprocessing_2eproto = {
  false, InitDefaults_video_5fprocessing_2eproto, 
  descriptor_table_protodef_video_5fprocessing_2eproto,
  "video_processing.proto", &assign_descriptors_table_video_5fprocessing_2eproto, 757,
};

void AddDescriptors_video_5fprocessing_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_video_5fprocessing_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_video_5fprocessing_2eproto = []() { AddDescriptors_video_5fprocessing_2eproto(); return true; }();
namespace video_processing {
const ::google::protobuf::EnumDescriptor* FrameType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&assign_descriptors_table_video_5fprocessing_2eproto);
  return file_level_enum_descriptors_video_5fprocessing_2eproto[0];
}
bool FrameType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* PixelFormat_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&assign_descriptors_table_video_5fprocessing_2eproto);
  return file_level_enum_descriptors_video_5fprocessing_2eproto[1];
}
bool PixelFormat_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* ImageEncoding_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&assign_descriptors_table_video_5fprocessing_2eproto);
  return file_level_enum_descriptors_video_5fprocessing_2eproto[2];
}
bool ImageEncoding_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void ImageData::InitAsDefaultInstance() {
}
class ImageData::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ImageData::kWidthFieldNumber;
const int ImageData::kHeightFieldNumber;
const int ImageData::kPixelFormatFieldNumber;
const int ImageData::kEncodingFieldNumber;
const int ImageData::kImageDataFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ImageData::ImageData()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:video_processing.ImageData)
}
ImageData::ImageData(const ImageData& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  image_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.image_data().size() > 0) {
    image_data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.image_data_);
  }
  ::memcpy(&width_, &from.width_,
    static_cast<size_t>(reinterpret_cast<char*>(&encoding_) -
    reinterpret_cast<char*>(&width_)) + sizeof(encoding_));
  // @@protoc_insertion_point(copy_constructor:video_processing.ImageData)
}

void ImageData::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_ImageData_video_5fprocessing_2eproto.base);
  image_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&width_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&encoding_) -
      reinterpret_cast<char*>(&width_)) + sizeof(encoding_));
}

ImageData::~ImageData() {
  // @@protoc_insertion_point(destructor:video_processing.ImageData)
  SharedDtor();
}

void ImageData::SharedDtor() {
  image_data_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ImageData::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ImageData& ImageData::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_ImageData_video_5fprocessing_2eproto.base);
  return *internal_default_instance();
}


void ImageData::Clear() {
// @@protoc_insertion_point(message_clear_start:video_processing.ImageData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  image_data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&width_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&encoding_) -
      reinterpret_cast<char*>(&width_)) + sizeof(encoding_));
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* ImageData::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<ImageData*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // uint32 width = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 8) goto handle_unusual;
        msg->set_width(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // uint32 height = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 16) goto handle_unusual;
        msg->set_height(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // .video_processing.PixelFormat pixel_format = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 24) goto handle_unusual;
        ::google::protobuf::uint64 val = ::google::protobuf::internal::ReadVarint(&ptr);
        msg->set_pixel_format(static_cast<::video_processing::PixelFormat>(val));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // .video_processing.ImageEncoding encoding = 4;
      case 4: {
        if (static_cast<::google::protobuf::uint8>(tag) != 32) goto handle_unusual;
        ::google::protobuf::uint64 val = ::google::protobuf::internal::ReadVarint(&ptr);
        msg->set_encoding(static_cast<::video_processing::ImageEncoding>(val));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // bytes image_data = 5;
      case 5: {
        if (static_cast<::google::protobuf::uint8>(tag) != 42) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        object = msg->mutable_image_data();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParser;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheck(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool ImageData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:video_processing.ImageData)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 width = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (8 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &width_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 height = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (16 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &height_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .video_processing.PixelFormat pixel_format = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (24 & 0xFF)) {
          int value = 0;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_pixel_format(static_cast< ::video_processing::PixelFormat >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .video_processing.ImageEncoding encoding = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (32 & 0xFF)) {
          int value = 0;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_encoding(static_cast< ::video_processing::ImageEncoding >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes image_data = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (42 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_image_data()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:video_processing.ImageData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:video_processing.ImageData)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void ImageData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:video_processing.ImageData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 width = 1;
  if (this->width() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->width(), output);
  }

  // uint32 height = 2;
  if (this->height() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->height(), output);
  }

  // .video_processing.PixelFormat pixel_format = 3;
  if (this->pixel_format() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->pixel_format(), output);
  }

  // .video_processing.ImageEncoding encoding = 4;
  if (this->encoding() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      4, this->encoding(), output);
  }

  // bytes image_data = 5;
  if (this->image_data().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      5, this->image_data(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:video_processing.ImageData)
}

::google::protobuf::uint8* ImageData::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:video_processing.ImageData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 width = 1;
  if (this->width() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->width(), target);
  }

  // uint32 height = 2;
  if (this->height() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->height(), target);
  }

  // .video_processing.PixelFormat pixel_format = 3;
  if (this->pixel_format() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      3, this->pixel_format(), target);
  }

  // .video_processing.ImageEncoding encoding = 4;
  if (this->encoding() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      4, this->encoding(), target);
  }

  // bytes image_data = 5;
  if (this->image_data().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        5, this->image_data(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:video_processing.ImageData)
  return target;
}

size_t ImageData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:video_processing.ImageData)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes image_data = 5;
  if (this->image_data().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->image_data());
  }

  // uint32 width = 1;
  if (this->width() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->width());
  }

  // uint32 height = 2;
  if (this->height() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->height());
  }

  // .video_processing.PixelFormat pixel_format = 3;
  if (this->pixel_format() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->pixel_format());
  }

  // .video_processing.ImageEncoding encoding = 4;
  if (this->encoding() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->encoding());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ImageData::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:video_processing.ImageData)
  GOOGLE_DCHECK_NE(&from, this);
  const ImageData* source =
      ::google::protobuf::DynamicCastToGenerated<ImageData>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:video_processing.ImageData)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:video_processing.ImageData)
    MergeFrom(*source);
  }
}

void ImageData::MergeFrom(const ImageData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:video_processing.ImageData)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.image_data().size() > 0) {

    image_data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.image_data_);
  }
  if (from.width() != 0) {
    set_width(from.width());
  }
  if (from.height() != 0) {
    set_height(from.height());
  }
  if (from.pixel_format() != 0) {
    set_pixel_format(from.pixel_format());
  }
  if (from.encoding() != 0) {
    set_encoding(from.encoding());
  }
}

void ImageData::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:video_processing.ImageData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ImageData::CopyFrom(const ImageData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:video_processing.ImageData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ImageData::IsInitialized() const {
  return true;
}

void ImageData::Swap(ImageData* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ImageData::InternalSwap(ImageData* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  image_data_.Swap(&other->image_data_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(width_, other->width_);
  swap(height_, other->height_);
  swap(pixel_format_, other->pixel_format_);
  swap(encoding_, other->encoding_);
}

::google::protobuf::Metadata ImageData::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_video_5fprocessing_2eproto);
  return ::file_level_metadata_video_5fprocessing_2eproto[kIndexInFileMessages];
}


// ===================================================================

void ImagePair::InitAsDefaultInstance() {
  ::video_processing::_ImagePair_default_instance_._instance.get_mutable()->original_ = const_cast< ::video_processing::ImageData*>(
      ::video_processing::ImageData::internal_default_instance());
  ::video_processing::_ImagePair_default_instance_._instance.get_mutable()->processed_ = const_cast< ::video_processing::ImageData*>(
      ::video_processing::ImageData::internal_default_instance());
}
class ImagePair::HasBitSetters {
 public:
  static const ::video_processing::ImageData& original(const ImagePair* msg);
  static const ::video_processing::ImageData& processed(const ImagePair* msg);
};

const ::video_processing::ImageData&
ImagePair::HasBitSetters::original(const ImagePair* msg) {
  return *msg->original_;
}
const ::video_processing::ImageData&
ImagePair::HasBitSetters::processed(const ImagePair* msg) {
  return *msg->processed_;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ImagePair::kOriginalFieldNumber;
const int ImagePair::kProcessedFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ImagePair::ImagePair()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:video_processing.ImagePair)
}
ImagePair::ImagePair(const ImagePair& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_original()) {
    original_ = new ::video_processing::ImageData(*from.original_);
  } else {
    original_ = nullptr;
  }
  if (from.has_processed()) {
    processed_ = new ::video_processing::ImageData(*from.processed_);
  } else {
    processed_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:video_processing.ImagePair)
}

void ImagePair::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_ImagePair_video_5fprocessing_2eproto.base);
  ::memset(&original_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&processed_) -
      reinterpret_cast<char*>(&original_)) + sizeof(processed_));
}

ImagePair::~ImagePair() {
  // @@protoc_insertion_point(destructor:video_processing.ImagePair)
  SharedDtor();
}

void ImagePair::SharedDtor() {
  if (this != internal_default_instance()) delete original_;
  if (this != internal_default_instance()) delete processed_;
}

void ImagePair::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ImagePair& ImagePair::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_ImagePair_video_5fprocessing_2eproto.base);
  return *internal_default_instance();
}


void ImagePair::Clear() {
// @@protoc_insertion_point(message_clear_start:video_processing.ImagePair)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == nullptr && original_ != nullptr) {
    delete original_;
  }
  original_ = nullptr;
  if (GetArenaNoVirtual() == nullptr && processed_ != nullptr) {
    delete processed_;
  }
  processed_ = nullptr;
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* ImagePair::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<ImagePair*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // .video_processing.ImageData original = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        parser_till_end = ::video_processing::ImageData::_InternalParse;
        object = msg->mutable_original();
        if (size > end - ptr) goto len_delim_till_end;
        ptr += size;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
            {parser_till_end, object}, ptr - size, ptr));
        break;
      }
      // .video_processing.ImageData processed = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 18) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        parser_till_end = ::video_processing::ImageData::_InternalParse;
        object = msg->mutable_processed();
        if (size > end - ptr) goto len_delim_till_end;
        ptr += size;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
            {parser_till_end, object}, ptr - size, ptr));
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool ImagePair::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:video_processing.ImagePair)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .video_processing.ImageData original = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_original()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .video_processing.ImageData processed = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (18 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_processed()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:video_processing.ImagePair)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:video_processing.ImagePair)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void ImagePair::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:video_processing.ImagePair)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .video_processing.ImageData original = 1;
  if (this->has_original()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, HasBitSetters::original(this), output);
  }

  // .video_processing.ImageData processed = 2;
  if (this->has_processed()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, HasBitSetters::processed(this), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:video_processing.ImagePair)
}

::google::protobuf::uint8* ImagePair::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:video_processing.ImagePair)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .video_processing.ImageData original = 1;
  if (this->has_original()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, HasBitSetters::original(this), target);
  }

  // .video_processing.ImageData processed = 2;
  if (this->has_processed()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, HasBitSetters::processed(this), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:video_processing.ImagePair)
  return target;
}

size_t ImagePair::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:video_processing.ImagePair)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .video_processing.ImageData original = 1;
  if (this->has_original()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *original_);
  }

  // .video_processing.ImageData processed = 2;
  if (this->has_processed()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *processed_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ImagePair::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:video_processing.ImagePair)
  GOOGLE_DCHECK_NE(&from, this);
  const ImagePair* source =
      ::google::protobuf::DynamicCastToGenerated<ImagePair>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:video_processing.ImagePair)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:video_processing.ImagePair)
    MergeFrom(*source);
  }
}

void ImagePair::MergeFrom(const ImagePair& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:video_processing.ImagePair)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_original()) {
    mutable_original()->::video_processing::ImageData::MergeFrom(from.original());
  }
  if (from.has_processed()) {
    mutable_processed()->::video_processing::ImageData::MergeFrom(from.processed());
  }
}

void ImagePair::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:video_processing.ImagePair)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ImagePair::CopyFrom(const ImagePair& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:video_processing.ImagePair)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ImagePair::IsInitialized() const {
  return true;
}

void ImagePair::Swap(ImagePair* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ImagePair::InternalSwap(ImagePair* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(original_, other->original_);
  swap(processed_, other->processed_);
}

::google::protobuf::Metadata ImagePair::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_video_5fprocessing_2eproto);
  return ::file_level_metadata_video_5fprocessing_2eproto[kIndexInFileMessages];
}


// ===================================================================

void VideoFrame::InitAsDefaultInstance() {
  ::video_processing::_VideoFrame_default_instance_.single_image_ = const_cast< ::video_processing::ImageData*>(
      ::video_processing::ImageData::internal_default_instance());
  ::video_processing::_VideoFrame_default_instance_.image_pair_ = const_cast< ::video_processing::ImagePair*>(
      ::video_processing::ImagePair::internal_default_instance());
  ::video_processing::_VideoFrame_default_instance_.command_.UnsafeSetDefault(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
class VideoFrame::HasBitSetters {
 public:
  static const ::video_processing::ImageData& single_image(const VideoFrame* msg);
  static const ::video_processing::ImagePair& image_pair(const VideoFrame* msg);
};

const ::video_processing::ImageData&
VideoFrame::HasBitSetters::single_image(const VideoFrame* msg) {
  return *msg->content_.single_image_;
}
const ::video_processing::ImagePair&
VideoFrame::HasBitSetters::image_pair(const VideoFrame* msg) {
  return *msg->content_.image_pair_;
}
void VideoFrame::set_allocated_single_image(::video_processing::ImageData* single_image) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  clear_content();
  if (single_image) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      single_image = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, single_image, submessage_arena);
    }
    set_has_single_image();
    content_.single_image_ = single_image;
  }
  // @@protoc_insertion_point(field_set_allocated:video_processing.VideoFrame.single_image)
}
void VideoFrame::set_allocated_image_pair(::video_processing::ImagePair* image_pair) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  clear_content();
  if (image_pair) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      image_pair = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, image_pair, submessage_arena);
    }
    set_has_image_pair();
    content_.image_pair_ = image_pair;
  }
  // @@protoc_insertion_point(field_set_allocated:video_processing.VideoFrame.image_pair)
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int VideoFrame::kFrameIdFieldNumber;
const int VideoFrame::kTimestampFieldNumber;
const int VideoFrame::kSenderIdFieldNumber;
const int VideoFrame::kFrameTypeFieldNumber;
const int VideoFrame::kSingleImageFieldNumber;
const int VideoFrame::kImagePairFieldNumber;
const int VideoFrame::kCommandFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

VideoFrame::VideoFrame()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:video_processing.VideoFrame)
}
VideoFrame::VideoFrame(const VideoFrame& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  sender_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.sender_id().size() > 0) {
    sender_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.sender_id_);
  }
  ::memcpy(&frame_id_, &from.frame_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&frame_type_) -
    reinterpret_cast<char*>(&frame_id_)) + sizeof(frame_type_));
  clear_has_content();
  switch (from.content_case()) {
    case kSingleImage: {
      mutable_single_image()->::video_processing::ImageData::MergeFrom(from.single_image());
      break;
    }
    case kImagePair: {
      mutable_image_pair()->::video_processing::ImagePair::MergeFrom(from.image_pair());
      break;
    }
    case kCommand: {
      set_command(from.command());
      break;
    }
    case CONTENT_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:video_processing.VideoFrame)
}

void VideoFrame::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_VideoFrame_video_5fprocessing_2eproto.base);
  sender_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&frame_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&frame_type_) -
      reinterpret_cast<char*>(&frame_id_)) + sizeof(frame_type_));
  clear_has_content();
}

VideoFrame::~VideoFrame() {
  // @@protoc_insertion_point(destructor:video_processing.VideoFrame)
  SharedDtor();
}

void VideoFrame::SharedDtor() {
  sender_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (has_content()) {
    clear_content();
  }
}

void VideoFrame::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const VideoFrame& VideoFrame::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_VideoFrame_video_5fprocessing_2eproto.base);
  return *internal_default_instance();
}


void VideoFrame::clear_content() {
// @@protoc_insertion_point(one_of_clear_start:video_processing.VideoFrame)
  switch (content_case()) {
    case kSingleImage: {
      delete content_.single_image_;
      break;
    }
    case kImagePair: {
      delete content_.image_pair_;
      break;
    }
    case kCommand: {
      content_.command_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
      break;
    }
    case CONTENT_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = CONTENT_NOT_SET;
}


void VideoFrame::Clear() {
// @@protoc_insertion_point(message_clear_start:video_processing.VideoFrame)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  sender_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&frame_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&frame_type_) -
      reinterpret_cast<char*>(&frame_id_)) + sizeof(frame_type_));
  clear_content();
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* VideoFrame::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<VideoFrame*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // uint64 frame_id = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 8) goto handle_unusual;
        msg->set_frame_id(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // double timestamp = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 17) goto handle_unusual;
        msg->set_timestamp(::google::protobuf::io::UnalignedLoad<double>(ptr));
        ptr += sizeof(double);
        break;
      }
      // string sender_id = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 26) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("video_processing.VideoFrame.sender_id");
        object = msg->mutable_sender_id();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // .video_processing.FrameType frame_type = 4;
      case 4: {
        if (static_cast<::google::protobuf::uint8>(tag) != 32) goto handle_unusual;
        ::google::protobuf::uint64 val = ::google::protobuf::internal::ReadVarint(&ptr);
        msg->set_frame_type(static_cast<::video_processing::FrameType>(val));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // .video_processing.ImageData single_image = 5;
      case 5: {
        if (static_cast<::google::protobuf::uint8>(tag) != 42) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        parser_till_end = ::video_processing::ImageData::_InternalParse;
        object = msg->mutable_single_image();
        if (size > end - ptr) goto len_delim_till_end;
        ptr += size;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
            {parser_till_end, object}, ptr - size, ptr));
        break;
      }
      // .video_processing.ImagePair image_pair = 6;
      case 6: {
        if (static_cast<::google::protobuf::uint8>(tag) != 50) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        parser_till_end = ::video_processing::ImagePair::_InternalParse;
        object = msg->mutable_image_pair();
        if (size > end - ptr) goto len_delim_till_end;
        ptr += size;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
            {parser_till_end, object}, ptr - size, ptr));
        break;
      }
      // string command = 7;
      case 7: {
        if (static_cast<::google::protobuf::uint8>(tag) != 58) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("video_processing.VideoFrame.command");
        object = msg->mutable_command();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool VideoFrame::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:video_processing.VideoFrame)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint64 frame_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (8 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &frame_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double timestamp = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (17 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &timestamp_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string sender_id = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (26 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_sender_id()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->sender_id().data(), static_cast<int>(this->sender_id().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "video_processing.VideoFrame.sender_id"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .video_processing.FrameType frame_type = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (32 & 0xFF)) {
          int value = 0;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_frame_type(static_cast< ::video_processing::FrameType >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .video_processing.ImageData single_image = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (42 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_single_image()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .video_processing.ImagePair image_pair = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (50 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_image_pair()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string command = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (58 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_command()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->command().data(), static_cast<int>(this->command().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "video_processing.VideoFrame.command"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:video_processing.VideoFrame)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:video_processing.VideoFrame)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void VideoFrame::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:video_processing.VideoFrame)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 frame_id = 1;
  if (this->frame_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->frame_id(), output);
  }

  // double timestamp = 2;
  if (this->timestamp() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->timestamp(), output);
  }

  // string sender_id = 3;
  if (this->sender_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->sender_id().data(), static_cast<int>(this->sender_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "video_processing.VideoFrame.sender_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->sender_id(), output);
  }

  // .video_processing.FrameType frame_type = 4;
  if (this->frame_type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      4, this->frame_type(), output);
  }

  // .video_processing.ImageData single_image = 5;
  if (has_single_image()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, HasBitSetters::single_image(this), output);
  }

  // .video_processing.ImagePair image_pair = 6;
  if (has_image_pair()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, HasBitSetters::image_pair(this), output);
  }

  // string command = 7;
  if (has_command()) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->command().data(), static_cast<int>(this->command().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "video_processing.VideoFrame.command");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->command(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:video_processing.VideoFrame)
}

::google::protobuf::uint8* VideoFrame::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:video_processing.VideoFrame)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 frame_id = 1;
  if (this->frame_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->frame_id(), target);
  }

  // double timestamp = 2;
  if (this->timestamp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->timestamp(), target);
  }

  // string sender_id = 3;
  if (this->sender_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->sender_id().data(), static_cast<int>(this->sender_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "video_processing.VideoFrame.sender_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->sender_id(), target);
  }

  // .video_processing.FrameType frame_type = 4;
  if (this->frame_type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      4, this->frame_type(), target);
  }

  // .video_processing.ImageData single_image = 5;
  if (has_single_image()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        5, HasBitSetters::single_image(this), target);
  }

  // .video_processing.ImagePair image_pair = 6;
  if (has_image_pair()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        6, HasBitSetters::image_pair(this), target);
  }

  // string command = 7;
  if (has_command()) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->command().data(), static_cast<int>(this->command().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "video_processing.VideoFrame.command");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->command(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:video_processing.VideoFrame)
  return target;
}

size_t VideoFrame::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:video_processing.VideoFrame)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string sender_id = 3;
  if (this->sender_id().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->sender_id());
  }

  // uint64 frame_id = 1;
  if (this->frame_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->frame_id());
  }

  // double timestamp = 2;
  if (this->timestamp() != 0) {
    total_size += 1 + 8;
  }

  // .video_processing.FrameType frame_type = 4;
  if (this->frame_type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->frame_type());
  }

  switch (content_case()) {
    // .video_processing.ImageData single_image = 5;
    case kSingleImage: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *content_.single_image_);
      break;
    }
    // .video_processing.ImagePair image_pair = 6;
    case kImagePair: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *content_.image_pair_);
      break;
    }
    // string command = 7;
    case kCommand: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->command());
      break;
    }
    case CONTENT_NOT_SET: {
      break;
    }
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void VideoFrame::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:video_processing.VideoFrame)
  GOOGLE_DCHECK_NE(&from, this);
  const VideoFrame* source =
      ::google::protobuf::DynamicCastToGenerated<VideoFrame>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:video_processing.VideoFrame)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:video_processing.VideoFrame)
    MergeFrom(*source);
  }
}

void VideoFrame::MergeFrom(const VideoFrame& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:video_processing.VideoFrame)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.sender_id().size() > 0) {

    sender_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.sender_id_);
  }
  if (from.frame_id() != 0) {
    set_frame_id(from.frame_id());
  }
  if (from.timestamp() != 0) {
    set_timestamp(from.timestamp());
  }
  if (from.frame_type() != 0) {
    set_frame_type(from.frame_type());
  }
  switch (from.content_case()) {
    case kSingleImage: {
      mutable_single_image()->::video_processing::ImageData::MergeFrom(from.single_image());
      break;
    }
    case kImagePair: {
      mutable_image_pair()->::video_processing::ImagePair::MergeFrom(from.image_pair());
      break;
    }
    case kCommand: {
      set_command(from.command());
      break;
    }
    case CONTENT_NOT_SET: {
      break;
    }
  }
}

void VideoFrame::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:video_processing.VideoFrame)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void VideoFrame::CopyFrom(const VideoFrame& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:video_processing.VideoFrame)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool VideoFrame::IsInitialized() const {
  return true;
}

void VideoFrame::Swap(VideoFrame* other) {
  if (other == this) return;
  InternalSwap(other);
}
void VideoFrame::InternalSwap(VideoFrame* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  sender_id_.Swap(&other->sender_id_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(frame_id_, other->frame_id_);
  swap(timestamp_, other->timestamp_);
  swap(frame_type_, other->frame_type_);
  swap(content_, other->content_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
}

::google::protobuf::Metadata VideoFrame::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_video_5fprocessing_2eproto);
  return ::file_level_metadata_video_5fprocessing_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace video_processing
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::video_processing::ImageData* Arena::CreateMaybeMessage< ::video_processing::ImageData >(Arena* arena) {
  return Arena::CreateInternal< ::video_processing::ImageData >(arena);
}
template<> PROTOBUF_NOINLINE ::video_processing::ImagePair* Arena::CreateMaybeMessage< ::video_processing::ImagePair >(Arena* arena) {
  return Arena::CreateInternal< ::video_processing::ImagePair >(arena);
}
template<> PROTOBUF_NOINLINE ::video_processing::VideoFrame* Arena::CreateMaybeMessage< ::video_processing::VideoFrame >(Arena* arena) {
  return Arena::CreateInternal< ::video_processing::VideoFrame >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
