// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: video_processing.proto

#ifndef PROTOBUF_INCLUDED_video_5fprocessing_2eproto
#define PROTOBUF_INCLUDED_video_5fprocessing_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_video_5fprocessing_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_video_5fprocessing_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_video_5fprocessing_2eproto();
namespace video_processing {
class ImageData;
class ImageDataDefaultTypeInternal;
extern ImageDataDefaultTypeInternal _ImageData_default_instance_;
class ImagePair;
class ImagePairDefaultTypeInternal;
extern ImagePairDefaultTypeInternal _ImagePair_default_instance_;
class VideoFrame;
class VideoFrameDefaultTypeInternal;
extern VideoFrameDefaultTypeInternal _VideoFrame_default_instance_;
}  // namespace video_processing
namespace google {
namespace protobuf {
template<> ::video_processing::ImageData* Arena::CreateMaybeMessage<::video_processing::ImageData>(Arena*);
template<> ::video_processing::ImagePair* Arena::CreateMaybeMessage<::video_processing::ImagePair>(Arena*);
template<> ::video_processing::VideoFrame* Arena::CreateMaybeMessage<::video_processing::VideoFrame>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace video_processing {

enum FrameType {
  UNKNOWN = 0,
  CAPTURED_FRAME = 1,
  PROCESSED_FRAME = 2,
  CONTROL_MESSAGE = 3,
  FrameType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::google::protobuf::int32>::min(),
  FrameType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::google::protobuf::int32>::max()
};
bool FrameType_IsValid(int value);
const FrameType FrameType_MIN = UNKNOWN;
const FrameType FrameType_MAX = CONTROL_MESSAGE;
const int FrameType_ARRAYSIZE = FrameType_MAX + 1;

const ::google::protobuf::EnumDescriptor* FrameType_descriptor();
inline const ::std::string& FrameType_Name(FrameType value) {
  return ::google::protobuf::internal::NameOfEnum(
    FrameType_descriptor(), value);
}
inline bool FrameType_Parse(
    const ::std::string& name, FrameType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<FrameType>(
    FrameType_descriptor(), name, value);
}
enum PixelFormat {
  BGR = 0,
  RGB = 1,
  GRAY = 2,
  PixelFormat_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::google::protobuf::int32>::min(),
  PixelFormat_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::google::protobuf::int32>::max()
};
bool PixelFormat_IsValid(int value);
const PixelFormat PixelFormat_MIN = BGR;
const PixelFormat PixelFormat_MAX = GRAY;
const int PixelFormat_ARRAYSIZE = PixelFormat_MAX + 1;

const ::google::protobuf::EnumDescriptor* PixelFormat_descriptor();
inline const ::std::string& PixelFormat_Name(PixelFormat value) {
  return ::google::protobuf::internal::NameOfEnum(
    PixelFormat_descriptor(), value);
}
inline bool PixelFormat_Parse(
    const ::std::string& name, PixelFormat* value) {
  return ::google::protobuf::internal::ParseNamedEnum<PixelFormat>(
    PixelFormat_descriptor(), name, value);
}
enum ImageEncoding {
  JPEG = 0,
  PNG = 1,
  RAW = 2,
  ImageEncoding_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::google::protobuf::int32>::min(),
  ImageEncoding_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::google::protobuf::int32>::max()
};
bool ImageEncoding_IsValid(int value);
const ImageEncoding ImageEncoding_MIN = JPEG;
const ImageEncoding ImageEncoding_MAX = RAW;
const int ImageEncoding_ARRAYSIZE = ImageEncoding_MAX + 1;

const ::google::protobuf::EnumDescriptor* ImageEncoding_descriptor();
inline const ::std::string& ImageEncoding_Name(ImageEncoding value) {
  return ::google::protobuf::internal::NameOfEnum(
    ImageEncoding_descriptor(), value);
}
inline bool ImageEncoding_Parse(
    const ::std::string& name, ImageEncoding* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ImageEncoding>(
    ImageEncoding_descriptor(), name, value);
}
// ===================================================================

class ImageData :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:video_processing.ImageData) */ {
 public:
  ImageData();
  virtual ~ImageData();

  ImageData(const ImageData& from);

  inline ImageData& operator=(const ImageData& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ImageData(ImageData&& from) noexcept
    : ImageData() {
    *this = ::std::move(from);
  }

  inline ImageData& operator=(ImageData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const ImageData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ImageData* internal_default_instance() {
    return reinterpret_cast<const ImageData*>(
               &_ImageData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ImageData* other);
  friend void swap(ImageData& a, ImageData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ImageData* New() const final {
    return CreateMaybeMessage<ImageData>(nullptr);
  }

  ImageData* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ImageData>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ImageData& from);
  void MergeFrom(const ImageData& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ImageData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes image_data = 5;
  void clear_image_data();
  static const int kImageDataFieldNumber = 5;
  const ::std::string& image_data() const;
  void set_image_data(const ::std::string& value);
  #if LANG_CXX11
  void set_image_data(::std::string&& value);
  #endif
  void set_image_data(const char* value);
  void set_image_data(const void* value, size_t size);
  ::std::string* mutable_image_data();
  ::std::string* release_image_data();
  void set_allocated_image_data(::std::string* image_data);

  // uint32 width = 1;
  void clear_width();
  static const int kWidthFieldNumber = 1;
  ::google::protobuf::uint32 width() const;
  void set_width(::google::protobuf::uint32 value);

  // uint32 height = 2;
  void clear_height();
  static const int kHeightFieldNumber = 2;
  ::google::protobuf::uint32 height() const;
  void set_height(::google::protobuf::uint32 value);

  // .video_processing.PixelFormat pixel_format = 3;
  void clear_pixel_format();
  static const int kPixelFormatFieldNumber = 3;
  ::video_processing::PixelFormat pixel_format() const;
  void set_pixel_format(::video_processing::PixelFormat value);

  // .video_processing.ImageEncoding encoding = 4;
  void clear_encoding();
  static const int kEncodingFieldNumber = 4;
  ::video_processing::ImageEncoding encoding() const;
  void set_encoding(::video_processing::ImageEncoding value);

  // @@protoc_insertion_point(class_scope:video_processing.ImageData)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr image_data_;
  ::google::protobuf::uint32 width_;
  ::google::protobuf::uint32 height_;
  int pixel_format_;
  int encoding_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_video_5fprocessing_2eproto;
};
// -------------------------------------------------------------------

class ImagePair :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:video_processing.ImagePair) */ {
 public:
  ImagePair();
  virtual ~ImagePair();

  ImagePair(const ImagePair& from);

  inline ImagePair& operator=(const ImagePair& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ImagePair(ImagePair&& from) noexcept
    : ImagePair() {
    *this = ::std::move(from);
  }

  inline ImagePair& operator=(ImagePair&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const ImagePair& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ImagePair* internal_default_instance() {
    return reinterpret_cast<const ImagePair*>(
               &_ImagePair_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(ImagePair* other);
  friend void swap(ImagePair& a, ImagePair& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ImagePair* New() const final {
    return CreateMaybeMessage<ImagePair>(nullptr);
  }

  ImagePair* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ImagePair>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ImagePair& from);
  void MergeFrom(const ImagePair& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ImagePair* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .video_processing.ImageData original = 1;
  bool has_original() const;
  void clear_original();
  static const int kOriginalFieldNumber = 1;
  const ::video_processing::ImageData& original() const;
  ::video_processing::ImageData* release_original();
  ::video_processing::ImageData* mutable_original();
  void set_allocated_original(::video_processing::ImageData* original);

  // .video_processing.ImageData processed = 2;
  bool has_processed() const;
  void clear_processed();
  static const int kProcessedFieldNumber = 2;
  const ::video_processing::ImageData& processed() const;
  ::video_processing::ImageData* release_processed();
  ::video_processing::ImageData* mutable_processed();
  void set_allocated_processed(::video_processing::ImageData* processed);

  // @@protoc_insertion_point(class_scope:video_processing.ImagePair)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::video_processing::ImageData* original_;
  ::video_processing::ImageData* processed_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_video_5fprocessing_2eproto;
};
// -------------------------------------------------------------------

class VideoFrame :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:video_processing.VideoFrame) */ {
 public:
  VideoFrame();
  virtual ~VideoFrame();

  VideoFrame(const VideoFrame& from);

  inline VideoFrame& operator=(const VideoFrame& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  VideoFrame(VideoFrame&& from) noexcept
    : VideoFrame() {
    *this = ::std::move(from);
  }

  inline VideoFrame& operator=(VideoFrame&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const VideoFrame& default_instance();

  enum ContentCase {
    kSingleImage = 5,
    kImagePair = 6,
    kCommand = 7,
    CONTENT_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const VideoFrame* internal_default_instance() {
    return reinterpret_cast<const VideoFrame*>(
               &_VideoFrame_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(VideoFrame* other);
  friend void swap(VideoFrame& a, VideoFrame& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline VideoFrame* New() const final {
    return CreateMaybeMessage<VideoFrame>(nullptr);
  }

  VideoFrame* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<VideoFrame>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const VideoFrame& from);
  void MergeFrom(const VideoFrame& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VideoFrame* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string sender_id = 3;
  void clear_sender_id();
  static const int kSenderIdFieldNumber = 3;
  const ::std::string& sender_id() const;
  void set_sender_id(const ::std::string& value);
  #if LANG_CXX11
  void set_sender_id(::std::string&& value);
  #endif
  void set_sender_id(const char* value);
  void set_sender_id(const char* value, size_t size);
  ::std::string* mutable_sender_id();
  ::std::string* release_sender_id();
  void set_allocated_sender_id(::std::string* sender_id);

  // uint64 frame_id = 1;
  void clear_frame_id();
  static const int kFrameIdFieldNumber = 1;
  ::google::protobuf::uint64 frame_id() const;
  void set_frame_id(::google::protobuf::uint64 value);

  // double timestamp = 2;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 2;
  double timestamp() const;
  void set_timestamp(double value);

  // .video_processing.FrameType frame_type = 4;
  void clear_frame_type();
  static const int kFrameTypeFieldNumber = 4;
  ::video_processing::FrameType frame_type() const;
  void set_frame_type(::video_processing::FrameType value);

  // .video_processing.ImageData single_image = 5;
  bool has_single_image() const;
  void clear_single_image();
  static const int kSingleImageFieldNumber = 5;
  const ::video_processing::ImageData& single_image() const;
  ::video_processing::ImageData* release_single_image();
  ::video_processing::ImageData* mutable_single_image();
  void set_allocated_single_image(::video_processing::ImageData* single_image);

  // .video_processing.ImagePair image_pair = 6;
  bool has_image_pair() const;
  void clear_image_pair();
  static const int kImagePairFieldNumber = 6;
  const ::video_processing::ImagePair& image_pair() const;
  ::video_processing::ImagePair* release_image_pair();
  ::video_processing::ImagePair* mutable_image_pair();
  void set_allocated_image_pair(::video_processing::ImagePair* image_pair);

  // string command = 7;
  private:
  bool has_command() const;
  public:
  void clear_command();
  static const int kCommandFieldNumber = 7;
  const ::std::string& command() const;
  void set_command(const ::std::string& value);
  #if LANG_CXX11
  void set_command(::std::string&& value);
  #endif
  void set_command(const char* value);
  void set_command(const char* value, size_t size);
  ::std::string* mutable_command();
  ::std::string* release_command();
  void set_allocated_command(::std::string* command);

  void clear_content();
  ContentCase content_case() const;
  // @@protoc_insertion_point(class_scope:video_processing.VideoFrame)
 private:
  class HasBitSetters;
  void set_has_single_image();
  void set_has_image_pair();
  void set_has_command();

  inline bool has_content() const;
  inline void clear_has_content();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr sender_id_;
  ::google::protobuf::uint64 frame_id_;
  double timestamp_;
  int frame_type_;
  union ContentUnion {
    ContentUnion() {}
    ::video_processing::ImageData* single_image_;
    ::video_processing::ImagePair* image_pair_;
    ::google::protobuf::internal::ArenaStringPtr command_;
  } content_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend struct ::TableStruct_video_5fprocessing_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ImageData

// uint32 width = 1;
inline void ImageData::clear_width() {
  width_ = 0u;
}
inline ::google::protobuf::uint32 ImageData::width() const {
  // @@protoc_insertion_point(field_get:video_processing.ImageData.width)
  return width_;
}
inline void ImageData::set_width(::google::protobuf::uint32 value) {
  
  width_ = value;
  // @@protoc_insertion_point(field_set:video_processing.ImageData.width)
}

// uint32 height = 2;
inline void ImageData::clear_height() {
  height_ = 0u;
}
inline ::google::protobuf::uint32 ImageData::height() const {
  // @@protoc_insertion_point(field_get:video_processing.ImageData.height)
  return height_;
}
inline void ImageData::set_height(::google::protobuf::uint32 value) {
  
  height_ = value;
  // @@protoc_insertion_point(field_set:video_processing.ImageData.height)
}

// .video_processing.PixelFormat pixel_format = 3;
inline void ImageData::clear_pixel_format() {
  pixel_format_ = 0;
}
inline ::video_processing::PixelFormat ImageData::pixel_format() const {
  // @@protoc_insertion_point(field_get:video_processing.ImageData.pixel_format)
  return static_cast< ::video_processing::PixelFormat >(pixel_format_);
}
inline void ImageData::set_pixel_format(::video_processing::PixelFormat value) {
  
  pixel_format_ = value;
  // @@protoc_insertion_point(field_set:video_processing.ImageData.pixel_format)
}

// .video_processing.ImageEncoding encoding = 4;
inline void ImageData::clear_encoding() {
  encoding_ = 0;
}
inline ::video_processing::ImageEncoding ImageData::encoding() const {
  // @@protoc_insertion_point(field_get:video_processing.ImageData.encoding)
  return static_cast< ::video_processing::ImageEncoding >(encoding_);
}
inline void ImageData::set_encoding(::video_processing::ImageEncoding value) {
  
  encoding_ = value;
  // @@protoc_insertion_point(field_set:video_processing.ImageData.encoding)
}

// bytes image_data = 5;
inline void ImageData::clear_image_data() {
  image_data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ImageData::image_data() const {
  // @@protoc_insertion_point(field_get:video_processing.ImageData.image_data)
  return image_data_.GetNoArena();
}
inline void ImageData::set_image_data(const ::std::string& value) {
  
  image_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:video_processing.ImageData.image_data)
}
#if LANG_CXX11
inline void ImageData::set_image_data(::std::string&& value) {
  
  image_data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:video_processing.ImageData.image_data)
}
#endif
inline void ImageData::set_image_data(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  image_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:video_processing.ImageData.image_data)
}
inline void ImageData::set_image_data(const void* value, size_t size) {
  
  image_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:video_processing.ImageData.image_data)
}
inline ::std::string* ImageData::mutable_image_data() {
  
  // @@protoc_insertion_point(field_mutable:video_processing.ImageData.image_data)
  return image_data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ImageData::release_image_data() {
  // @@protoc_insertion_point(field_release:video_processing.ImageData.image_data)
  
  return image_data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ImageData::set_allocated_image_data(::std::string* image_data) {
  if (image_data != nullptr) {
    
  } else {
    
  }
  image_data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), image_data);
  // @@protoc_insertion_point(field_set_allocated:video_processing.ImageData.image_data)
}

// -------------------------------------------------------------------

// ImagePair

// .video_processing.ImageData original = 1;
inline bool ImagePair::has_original() const {
  return this != internal_default_instance() && original_ != nullptr;
}
inline void ImagePair::clear_original() {
  if (GetArenaNoVirtual() == nullptr && original_ != nullptr) {
    delete original_;
  }
  original_ = nullptr;
}
inline const ::video_processing::ImageData& ImagePair::original() const {
  const ::video_processing::ImageData* p = original_;
  // @@protoc_insertion_point(field_get:video_processing.ImagePair.original)
  return p != nullptr ? *p : *reinterpret_cast<const ::video_processing::ImageData*>(
      &::video_processing::_ImageData_default_instance_);
}
inline ::video_processing::ImageData* ImagePair::release_original() {
  // @@protoc_insertion_point(field_release:video_processing.ImagePair.original)
  
  ::video_processing::ImageData* temp = original_;
  original_ = nullptr;
  return temp;
}
inline ::video_processing::ImageData* ImagePair::mutable_original() {
  
  if (original_ == nullptr) {
    auto* p = CreateMaybeMessage<::video_processing::ImageData>(GetArenaNoVirtual());
    original_ = p;
  }
  // @@protoc_insertion_point(field_mutable:video_processing.ImagePair.original)
  return original_;
}
inline void ImagePair::set_allocated_original(::video_processing::ImageData* original) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete original_;
  }
  if (original) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      original = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, original, submessage_arena);
    }
    
  } else {
    
  }
  original_ = original;
  // @@protoc_insertion_point(field_set_allocated:video_processing.ImagePair.original)
}

// .video_processing.ImageData processed = 2;
inline bool ImagePair::has_processed() const {
  return this != internal_default_instance() && processed_ != nullptr;
}
inline void ImagePair::clear_processed() {
  if (GetArenaNoVirtual() == nullptr && processed_ != nullptr) {
    delete processed_;
  }
  processed_ = nullptr;
}
inline const ::video_processing::ImageData& ImagePair::processed() const {
  const ::video_processing::ImageData* p = processed_;
  // @@protoc_insertion_point(field_get:video_processing.ImagePair.processed)
  return p != nullptr ? *p : *reinterpret_cast<const ::video_processing::ImageData*>(
      &::video_processing::_ImageData_default_instance_);
}
inline ::video_processing::ImageData* ImagePair::release_processed() {
  // @@protoc_insertion_point(field_release:video_processing.ImagePair.processed)
  
  ::video_processing::ImageData* temp = processed_;
  processed_ = nullptr;
  return temp;
}
inline ::video_processing::ImageData* ImagePair::mutable_processed() {
  
  if (processed_ == nullptr) {
    auto* p = CreateMaybeMessage<::video_processing::ImageData>(GetArenaNoVirtual());
    processed_ = p;
  }
  // @@protoc_insertion_point(field_mutable:video_processing.ImagePair.processed)
  return processed_;
}
inline void ImagePair::set_allocated_processed(::video_processing::ImageData* processed) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete processed_;
  }
  if (processed) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      processed = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, processed, submessage_arena);
    }
    
  } else {
    
  }
  processed_ = processed;
  // @@protoc_insertion_point(field_set_allocated:video_processing.ImagePair.processed)
}

// -------------------------------------------------------------------

// VideoFrame

// uint64 frame_id = 1;
inline void VideoFrame::clear_frame_id() {
  frame_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 VideoFrame::frame_id() const {
  // @@protoc_insertion_point(field_get:video_processing.VideoFrame.frame_id)
  return frame_id_;
}
inline void VideoFrame::set_frame_id(::google::protobuf::uint64 value) {
  
  frame_id_ = value;
  // @@protoc_insertion_point(field_set:video_processing.VideoFrame.frame_id)
}

// double timestamp = 2;
inline void VideoFrame::clear_timestamp() {
  timestamp_ = 0;
}
inline double VideoFrame::timestamp() const {
  // @@protoc_insertion_point(field_get:video_processing.VideoFrame.timestamp)
  return timestamp_;
}
inline void VideoFrame::set_timestamp(double value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:video_processing.VideoFrame.timestamp)
}

// string sender_id = 3;
inline void VideoFrame::clear_sender_id() {
  sender_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& VideoFrame::sender_id() const {
  // @@protoc_insertion_point(field_get:video_processing.VideoFrame.sender_id)
  return sender_id_.GetNoArena();
}
inline void VideoFrame::set_sender_id(const ::std::string& value) {
  
  sender_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:video_processing.VideoFrame.sender_id)
}
#if LANG_CXX11
inline void VideoFrame::set_sender_id(::std::string&& value) {
  
  sender_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:video_processing.VideoFrame.sender_id)
}
#endif
inline void VideoFrame::set_sender_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  sender_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:video_processing.VideoFrame.sender_id)
}
inline void VideoFrame::set_sender_id(const char* value, size_t size) {
  
  sender_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:video_processing.VideoFrame.sender_id)
}
inline ::std::string* VideoFrame::mutable_sender_id() {
  
  // @@protoc_insertion_point(field_mutable:video_processing.VideoFrame.sender_id)
  return sender_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* VideoFrame::release_sender_id() {
  // @@protoc_insertion_point(field_release:video_processing.VideoFrame.sender_id)
  
  return sender_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void VideoFrame::set_allocated_sender_id(::std::string* sender_id) {
  if (sender_id != nullptr) {
    
  } else {
    
  }
  sender_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), sender_id);
  // @@protoc_insertion_point(field_set_allocated:video_processing.VideoFrame.sender_id)
}

// .video_processing.FrameType frame_type = 4;
inline void VideoFrame::clear_frame_type() {
  frame_type_ = 0;
}
inline ::video_processing::FrameType VideoFrame::frame_type() const {
  // @@protoc_insertion_point(field_get:video_processing.VideoFrame.frame_type)
  return static_cast< ::video_processing::FrameType >(frame_type_);
}
inline void VideoFrame::set_frame_type(::video_processing::FrameType value) {
  
  frame_type_ = value;
  // @@protoc_insertion_point(field_set:video_processing.VideoFrame.frame_type)
}

// .video_processing.ImageData single_image = 5;
inline bool VideoFrame::has_single_image() const {
  return content_case() == kSingleImage;
}
inline void VideoFrame::set_has_single_image() {
  _oneof_case_[0] = kSingleImage;
}
inline void VideoFrame::clear_single_image() {
  if (has_single_image()) {
    delete content_.single_image_;
    clear_has_content();
  }
}
inline ::video_processing::ImageData* VideoFrame::release_single_image() {
  // @@protoc_insertion_point(field_release:video_processing.VideoFrame.single_image)
  if (has_single_image()) {
    clear_has_content();
      ::video_processing::ImageData* temp = content_.single_image_;
    content_.single_image_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::video_processing::ImageData& VideoFrame::single_image() const {
  // @@protoc_insertion_point(field_get:video_processing.VideoFrame.single_image)
  return has_single_image()
      ? *content_.single_image_
      : *reinterpret_cast< ::video_processing::ImageData*>(&::video_processing::_ImageData_default_instance_);
}
inline ::video_processing::ImageData* VideoFrame::mutable_single_image() {
  if (!has_single_image()) {
    clear_content();
    set_has_single_image();
    content_.single_image_ = CreateMaybeMessage< ::video_processing::ImageData >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:video_processing.VideoFrame.single_image)
  return content_.single_image_;
}

// .video_processing.ImagePair image_pair = 6;
inline bool VideoFrame::has_image_pair() const {
  return content_case() == kImagePair;
}
inline void VideoFrame::set_has_image_pair() {
  _oneof_case_[0] = kImagePair;
}
inline void VideoFrame::clear_image_pair() {
  if (has_image_pair()) {
    delete content_.image_pair_;
    clear_has_content();
  }
}
inline ::video_processing::ImagePair* VideoFrame::release_image_pair() {
  // @@protoc_insertion_point(field_release:video_processing.VideoFrame.image_pair)
  if (has_image_pair()) {
    clear_has_content();
      ::video_processing::ImagePair* temp = content_.image_pair_;
    content_.image_pair_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::video_processing::ImagePair& VideoFrame::image_pair() const {
  // @@protoc_insertion_point(field_get:video_processing.VideoFrame.image_pair)
  return has_image_pair()
      ? *content_.image_pair_
      : *reinterpret_cast< ::video_processing::ImagePair*>(&::video_processing::_ImagePair_default_instance_);
}
inline ::video_processing::ImagePair* VideoFrame::mutable_image_pair() {
  if (!has_image_pair()) {
    clear_content();
    set_has_image_pair();
    content_.image_pair_ = CreateMaybeMessage< ::video_processing::ImagePair >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:video_processing.VideoFrame.image_pair)
  return content_.image_pair_;
}

// string command = 7;
inline bool VideoFrame::has_command() const {
  return content_case() == kCommand;
}
inline void VideoFrame::set_has_command() {
  _oneof_case_[0] = kCommand;
}
inline void VideoFrame::clear_command() {
  if (has_command()) {
    content_.command_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    clear_has_content();
  }
}
inline const ::std::string& VideoFrame::command() const {
  // @@protoc_insertion_point(field_get:video_processing.VideoFrame.command)
  if (has_command()) {
    return content_.command_.GetNoArena();
  }
  return *&::google::protobuf::internal::GetEmptyStringAlreadyInited();
}
inline void VideoFrame::set_command(const ::std::string& value) {
  // @@protoc_insertion_point(field_set:video_processing.VideoFrame.command)
  if (!has_command()) {
    clear_content();
    set_has_command();
    content_.command_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  content_.command_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:video_processing.VideoFrame.command)
}
#if LANG_CXX11
inline void VideoFrame::set_command(::std::string&& value) {
  // @@protoc_insertion_point(field_set:video_processing.VideoFrame.command)
  if (!has_command()) {
    clear_content();
    set_has_command();
    content_.command_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  content_.command_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:video_processing.VideoFrame.command)
}
#endif
inline void VideoFrame::set_command(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  if (!has_command()) {
    clear_content();
    set_has_command();
    content_.command_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  content_.command_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value));
  // @@protoc_insertion_point(field_set_char:video_processing.VideoFrame.command)
}
inline void VideoFrame::set_command(const char* value, size_t size) {
  if (!has_command()) {
    clear_content();
    set_has_command();
    content_.command_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  content_.command_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:video_processing.VideoFrame.command)
}
inline ::std::string* VideoFrame::mutable_command() {
  if (!has_command()) {
    clear_content();
    set_has_command();
    content_.command_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_mutable:video_processing.VideoFrame.command)
  return content_.command_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* VideoFrame::release_command() {
  // @@protoc_insertion_point(field_release:video_processing.VideoFrame.command)
  if (has_command()) {
    clear_has_content();
    return content_.command_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  } else {
    return nullptr;
  }
}
inline void VideoFrame::set_allocated_command(::std::string* command) {
  if (has_content()) {
    clear_content();
  }
  if (command != nullptr) {
    set_has_command();
    content_.command_.UnsafeSetDefault(command);
  }
  // @@protoc_insertion_point(field_set_allocated:video_processing.VideoFrame.command)
}

inline bool VideoFrame::has_content() const {
  return content_case() != CONTENT_NOT_SET;
}
inline void VideoFrame::clear_has_content() {
  _oneof_case_[0] = CONTENT_NOT_SET;
}
inline VideoFrame::ContentCase VideoFrame::content_case() const {
  return VideoFrame::ContentCase(_oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace video_processing

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::video_processing::FrameType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::video_processing::FrameType>() {
  return ::video_processing::FrameType_descriptor();
}
template <> struct is_proto_enum< ::video_processing::PixelFormat> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::video_processing::PixelFormat>() {
  return ::video_processing::PixelFormat_descriptor();
}
template <> struct is_proto_enum< ::video_processing::ImageEncoding> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::video_processing::ImageEncoding>() {
  return ::video_processing::ImageEncoding_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_video_5fprocessing_2eproto
